#!/usr/bin/env bash
set -euo pipefail

# Generates docker/.env (gitignored) so `docker compose`/`docker compose run --rm` mount the
# shared trntest_ws cache/scratch and a per-worktree output/ subfolder, use a per-worktree image
# tag/project name, and (if a worktree agent chooses to run its own `docker compose up` Jupyter Lab
# server alongside the main checkout's) a per-worktree port -- see docker-compose.yml's top comment
# and docs/environment.md's "Multi-agent worktrees" section for why. Run once after creating/
# entering a new worktree, before the first `docker compose` invocation there. Safe to re-run any
# time (idempotent, overwrites).

repo_root="$(git rev-parse --show-toplevel)"
common_dir="$(git rev-parse --path-format=absolute --git-common-dir)"
# .git's parent is the main checkout root (<workspace>/src/trntest) regardless of which
# worktree this script is actually run from -- git worktrees all share one .git.
main_checkout="$(dirname "$common_dir")"
workspace_root="$(dirname "$(dirname "$main_checkout")")"
env_file="$repo_root/docker/.env"

if [[ "$repo_root" == "$main_checkout" ]]; then
    # Main checkout: docker-compose.yml's built-in defaults already suit it (relative mounts,
    # shared image tag, port 8888). Remove any stale override file so it can't leave behind
    # values from a prior experiment.
    rm -f "$env_file"
    echo "Main checkout detected -- removed $env_file (if present); using docker-compose.yml's built-in defaults."
    exit 0
fi

name="$(basename "$repo_root")"
mkdir -p "$workspace_root/output/$name"

# TRNTEST_MAIN_GIT_DIR must match the *literal* path git's own worktree admin files store
# internally, which `git rev-parse --git-common-dir` may have silently resolved through a symlink
# (e.g. after trntest_ws was relocated onto a new block device with a compatibility symlink left at
# its old path -- see docs/environment.md's "Multi-agent worktrees" section) -- read it straight out
# of this worktree's own `.git` file instead of trusting rev-parse's resolution, since that's
# exactly the (possibly still-symlinked) string a containerized git process will try to open.
literal_gitdir="$(sed -n 's/^gitdir: //p' "$repo_root/.git")"
literal_common_dir="$(dirname "$(dirname "$literal_gitdir")")"

# Jupyter Lab port convention: 8887 + <agent number>, where the agent number is the worktree
# name's own trailing digits (e.g. "a1" -> 8888, "a2" -> 8889) -- keeps each active worktree
# agent's own `docker compose up` server (the normal way to run one in practice; see
# docs/environment.md's "Multi-agent worktrees" section) off each other's port, without requiring
# manual coordination between concurrently-running agents. Falls back to leaving
# TRNTEST_JUPYTER_PORT unset (docker-compose.yml's own default, 8888 -- just its unvaried value,
# not a claim that the main checkout has anything running there) if the worktree name doesn't end
# in digits, rather than guessing.
port_line=""
if [[ "$name" =~ ([0-9]+)$ ]]; then
    port=$((8887 + 10#${BASH_REMATCH[1]}))
    port_line="TRNTEST_JUPYTER_PORT=$port"
else
    echo "Worktree name \"$name\" has no trailing digits -- skipping TRNTEST_JUPYTER_PORT" \
        "(docker-compose.yml's own 8888 default applies; set it manually in $env_file if you run" \
        "docker compose up here)."
fi

cat > "$env_file" <<EOF
# Generated by scripts/setup_worktree_docker_env.sh for worktree "$name" -- gitignored, safe to
# regenerate, do not commit.
COMPOSE_PROJECT_NAME=trntest-$name
TRNTEST_IMAGE_TAG=trntest-lunar-demo-$name
TRNTEST_HOST_CACHE_DIR=$workspace_root/cache
TRNTEST_HOST_OUTPUT_DIR=$workspace_root/output/$name
TRNTEST_HOST_SCRATCH_DIR=$workspace_root/scratch
TRNTEST_MAIN_GIT_DIR=$literal_common_dir
$port_line
EOF

echo "Wrote $env_file for worktree \"$name\":"
cat "$env_file"
