#!/usr/bin/env bash
set -euo pipefail

# Generates docker/.env (gitignored) so `docker compose`/`docker compose run --rm` mount the
# shared trntest_ws cache/scratch and a per-worktree output/ subfolder, use a per-worktree image
# tag/project name, and (if a worktree agent chooses to run its own `docker compose up` Jupyter Lab
# server alongside the main checkout's) a per-worktree port -- see docker-compose.yml's top comment
# and docs/environment.md's "Multi-agent worktrees" section for why. Run once after creating/
# entering a new worktree, before the first `docker compose` invocation there. Safe to re-run any
# time (idempotent, overwrites).

repo_root="$(git rev-parse --show-toplevel)"
common_dir="$(git rev-parse --path-format=absolute --git-common-dir)"
# .git's parent is the main checkout root (<workspace>/src/trntest) regardless of which
# worktree this script is actually run from -- git worktrees all share one .git.
main_checkout="$(dirname "$common_dir")"
workspace_root="$(dirname "$(dirname "$main_checkout")")"
env_file="$repo_root/docker/.env"

if [[ "$repo_root" == "$main_checkout" ]]; then
    # Main checkout: docker-compose.yml's built-in defaults already suit it (relative mounts,
    # shared image tag, port 8888). Remove any stale override file so it can't leave behind
    # values from a prior experiment.
    rm -f "$env_file"
    echo "Main checkout detected -- removed $env_file (if present); using docker-compose.yml's built-in defaults."
    exit 0
fi

name="$(basename "$repo_root")"
mkdir -p "$workspace_root/output/$name"

# TRNTEST_MAIN_GIT_DIR must match the *literal* path git's own worktree admin files store
# internally, which `git rev-parse --git-common-dir` may have silently resolved through a symlink
# (e.g. after trntest_ws was relocated onto a new block device with a compatibility symlink left at
# its old path -- see docs/environment.md's "Multi-agent worktrees" section) -- read it straight out
# of this worktree's own `.git` file instead of trusting rev-parse's resolution, since that's
# exactly the (possibly still-symlinked) string a containerized git process will try to open.
literal_gitdir="$(sed -n 's/^gitdir: //p' "$repo_root/.git")"
literal_common_dir="$(dirname "$(dirname "$literal_gitdir")")"

# Jupyter Lab port: the lowest port >= 8888 that no other worktree's docker/.env claims and nothing
# is listening on, so the user can keep one SSH command forwarding 8888, 8889, ... for whichever
# agents are active. Checking other worktrees' .env files, not just listeners, covers a peer that
# ran this script but hasn't started its server yet. Re-running keeps this worktree's existing port
# if no other worktree claims it (a listener on it may be this worktree's own server).
claimed_ports() {
    local wt
    git worktree list --porcelain | sed -n 's/^worktree //p' | while read -r wt; do
        [[ "$wt" -ef "$repo_root" ]] && continue
        sed -n 's/^TRNTEST_JUPYTER_PORT=//p' "$wt/docker/.env" 2>/dev/null || true
    done
}
claimed=" $(claimed_ports | tr '\n' ' ') "
listening=" $(ss -Hltn 2>/dev/null | awk '{print $4}' | sed 's/.*://' | tr '\n' ' ') "
port="$(sed -n 's/^TRNTEST_JUPYTER_PORT=//p' "$env_file" 2>/dev/null || true)"
if ! [[ "$port" =~ ^[0-9]+$ ]] || ((port < 8888 || port > 65535)) || [[ "$claimed" == *" $port "* ]]; then
    port=8888
    while [[ "$claimed" == *" $port "* || "$listening" == *" $port "* ]]; do
        port=$((port + 1))
    done
fi
port_line="TRNTEST_JUPYTER_PORT=$port"

cat > "$env_file" <<EOF
# Generated by scripts/setup_worktree_docker_env.sh for worktree "$name" -- gitignored, safe to
# regenerate, do not commit.
COMPOSE_PROJECT_NAME=trntest-$name
TRNTEST_IMAGE_TAG=trntest-lunar-demo-$name
TRNTEST_HOST_CACHE_DIR=$workspace_root/cache
TRNTEST_HOST_OUTPUT_DIR=$workspace_root/output/$name
TRNTEST_HOST_OUTPUT_GLOBAL_DIR=$workspace_root/output
TRNTEST_HOST_SCRATCH_DIR=$workspace_root/scratch
TRNTEST_MAIN_GIT_DIR=$literal_common_dir
$port_line
EOF

echo "Wrote $env_file for worktree \"$name\":"
cat "$env_file"
