#!/usr/bin/env bash
set -euo pipefail

# Generates docker/.env (gitignored) so `docker compose`/`docker compose run --rm` mount the
# shared trntest_ws cache/scratch and a per-worktree output/ subfolder, use a per-worktree image
# tag/project name, and (TRNTEST_MAIN_GIT_DIR) let git actually work inside the container for a
# worktree checkout -- see docker-compose.yml's top comment and docs/environment.md's "Multi-agent
# worktrees" section for why. Run once after creating/entering a new worktree, before the first
# `docker compose` invocation there. Safe to re-run any time (idempotent, overwrites).

repo_root="$(git rev-parse --show-toplevel)"
common_dir="$(git rev-parse --path-format=absolute --git-common-dir)"
# .git's parent is the main checkout root (<workspace>/src/trntest) regardless of which
# worktree this script is actually run from -- git worktrees all share one .git.
main_checkout="$(dirname "$common_dir")"
workspace_root="$(dirname "$(dirname "$main_checkout")")"
env_file="$repo_root/docker/.env"

if [[ "$repo_root" == "$main_checkout" ]]; then
    # Main checkout: docker-compose.yml's built-in defaults already suit it (relative mounts,
    # shared image tag, port 8888). Remove any stale override file so it can't leave behind
    # values from a prior experiment.
    rm -f "$env_file"
    echo "Main checkout detected -- removed $env_file (if present); using docker-compose.yml's built-in defaults."
    exit 0
fi

name="$(basename "$repo_root")"
mkdir -p "$workspace_root/output/$name"

cat > "$env_file" <<EOF
# Generated by scripts/setup_worktree_docker_env.sh for worktree "$name" -- gitignored, safe to
# regenerate, do not commit.
COMPOSE_PROJECT_NAME=trntest-$name
TRNTEST_IMAGE_TAG=trntest-lunar-demo-$name
TRNTEST_HOST_CACHE_DIR=$workspace_root/cache
TRNTEST_HOST_OUTPUT_DIR=$workspace_root/output/$name
TRNTEST_HOST_SCRATCH_DIR=$workspace_root/scratch
TRNTEST_MAIN_GIT_DIR=$common_dir
EOF

echo "Wrote $env_file for worktree \"$name\":"
cat "$env_file"
